require: rubocop-rails

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20

Metrics/CyclomaticComplexity:
  Max: 10



AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/**'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
