require: rubocop-rails

Layout/LineLength:
  Max: 120

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false
